### ISSUE TITLE
Compile issue with generic arguments

### ISSUE THREAD

**Issue by JelteF** [crlf0710/delegatemethod-rs#1]
Thanks for the great crate. It helps a lot in reducing boilerplate. I'm having the issue that I am getting an error with the following code:
```rust
    delegate_method!{
        impl<K: Eq + std::hash::Hash, V: Clone> DefaultHashMap<K, V> {
            map as HashMap:
                pub fn remove<Q: ?Sized>(&mut self, k: &Q) -> Option<V>
                    where K: Borrow<Q>,
                          Q: Hash + Eq;
        }
    }
```
This is the error:
```
error: no rules expected the token `impl_expansion`
  --> src/lib.rs:50:5
   |
50 |       delegate_method!{
   |  _____^ starting here...
51 | |         impl<K: Eq + std::hash::Hash, V: Clone> DefaultHashMap<K, V> {
52 | |             map as HashMap:
53 | |                 pub fn remove<Q: ?Sized>(&mut self, k: &Q) -> Option<V>
54 | |                     where K: Borrow<Q>,
55 | |                           Q: Hash + Eq;
56 | |         }
57 | |     }
   | |_____^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate
error: Could not compile `defaultmap`.
```

**Comment by JelteF** [comment]
After investigating a bit more I've found that there's multiple things that cause this issue. The first is that no bounds are supported inside the `<>`, only after the where. It works to just move the bound there normally. However, the `?Sized` bound is special and is not supported even there.

**Comment by crlf0710** [comment]
Hi, thanks for the report! Yes i can reproduce the problem, and it's a parsing issue. I'll fix it shortly.

However, as you could see, this project is largely experimental. It is only a temporary workaround for the lack of https://github.com/rust-lang/rfcs/pull/1406 . I'll suggest that do not use this crate for anything larger than the simplest programs.

**Comment by JelteF** [comment]
Good to hear, I tried a simple fix for the `<>` problem but it broke lifetimes so I gave up again (just so you know). 

And I understand why you would say that this project should not be used for larger projects, but it really works quite well for simple function signatures at least (which are already like 3/4ths of the cases I have).

**Comment by crlf0710** [comment]
Hi, i've uploaded a new version. It treats the ?Size bound specially so it's ok to use it as the first trait in each bound in the where clause. You can't use it after a + though.

**Comment by JelteF** [comment]
I just tried it out and it works partially. I can't get it to work when there's two traits like this:
```rust
    delegate_method!{
        impl<K: Eq + std::hash::Hash, V: Clone> DefaultHashMap<K, V> {
            map as HashMap:
                pub fn remove<Q>(&mut self, k: &Q) -> Option<V>
                    where Q: Sized? + Hash + Eq, K: Borrow<Q>;
        }
    }
```

**Comment by crlf0710** [comment]
@JelteF just turn everything into a where clause

**Comment by crlf0710** [comment]
@JelteF  I think you meant `?Sized` right? and we can't support parsing `Borrow<Q>`(things with angle brackets)  in where clauses now, sorry :(

**Comment by crlf0710** [comment]
If we reimplement this using proc macro 1.1 and proc_macro_hack, we would be able to fully support everything in theory... Just not sure whether it's worth it.

**Comment by Boscop** [comment]
> If we reimplement this using proc macro 1.1 and proc_macro_hack, we would be able to fully support everything in theory... Just not sure whether it's worth it.

I think it's worth it!
A lot of other people are interested in delegation too:
https://github.com/rust-lang/rfcs/pull/1406#issuecomment-360384139 (see last comments)
https://internals.rust-lang.org/t/new-rfc-for-delegation-anyone-interested-in-contributing/6644/5
https://internals.rust-lang.org/t/3-weeks-to-delegation-please-help/5742
https://internals.rust-lang.org/t/delegate-trait-implementations-with-procedural-macros/6357

I think it would be useful to have this in the language itself, but that will take a long time if it ever happens, and in the meantime it would be useful to have it in a library.

The macro could work in several convenient ways:
1. Expose all methods of the member as delegated methods
2. Expose only pub methods of the member as delegated methods
3. Expose only the given list of methods of the member as delegated methods

If 1. and 2. are not possible with proc-macros, only having option 3. would already be a huge step forward.
